server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/authdb
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET:c2VjcmV0LWtleS1mb3ItaWJhbmtpbmctcHJvamVjdA==}
  expiration: 86400000

internal:
  api-key: ${INTERNAL_API_KEY}

# đã đổi lại pass word cho đúng P24