server:
  port: 8084

spring:
  application:
    name: notification-service
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}
    listener:
      simple:
        default-requeue-rejected: false
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${EMAIL_USER:}
    password: ${EMAIL_PASS:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
